version: '3.3'

services:
    frontend:
        build:
            context: .
            dockerfile: docker/Dockerfile
        tty: true
        volumes:
            - .:/app
        ports:
            - 5173:5173
        # command: sh -c "pnpm install && pnpm run dev"
